#!/bin/bash
buildobj="myapp"
buildstage="latest"

docker rmi ${buildobj}:${buildstage}
docker build -t ${buildobj}:${buildstage} .
#docker push ${buildobj}:${buildstage}
docker run --rm -h $buildobj --name $buildobj -v $PWD/ctrl:/ctrl -it ${buildobj}:${buildstage}

